import { defineConfig } from 'vite';

/**
 * Bundles the API (server/ plus the game simulation it replays) into one self-contained ES module,
 * api/game.js, which Vercel deploys as a Node.js Function. Run with `npm run build:api`.
 * The output is committed so the deployment never depends on build order; CI checks it is up to date.
 */
export default defineConfig({
  publicDir: false,
  build: {
    ssr: 'server/index.ts',
    outDir: 'api',
    emptyOutDir: false,
    target: 'node20',
    minify: false,
    reportCompressedSize: false,
    rollupOptions: {
      output: {
        format: 'es',
        entryFileNames: 'game.js',
        banner: '// GENERATED by `npm run build:api` from server/ - do not edit by hand.',
      },
    },
  },
  ssr: { noExternal: true, target: 'node' },
});
