/**
 * Food pixel art. Every dish on the SRM menu gets its own 12x12 sprite (drawn as text, shaded with a
 * highlight on the top-left and a shadow on the bottom-right). Colour letters live in PALETTE (art.ts).
 * Related dishes reuse one drawing with a colour `swap` (e.g. fried rice = pulao in brown tones).
 */
import type { SpriteDef } from './art';

const PULAO = [
  '....hhhh....',
  '..hhohhhhh..',
  '.hhhhhghhhh.',
  '.hohhhhhhoh.',
  'hhhhhhghhhhh',
  'hhahhhhhahhh',
  'ssssssssssss',
  '.zzzzzzzzzz.',
];

const RASAM = [
  '..s..s......',
  '...s..s.....',
  '.wwwwwwwwww.',
  'wrrrorrrrrrw',
  'wrorrrrrorrw',
  '.wrrrrrrrrw.',
  '..wwwwwwww..',
  '...ssssss...',
];

const DAL = [
  '...s..s.....',
  '....s..s....',
  '.nnnnnnnnnn.',
  'nyyyyyyyyyyn',
  'nyyjyyrjyyyn',
  'nyyyyjyyyyyn',
  '.nyyyyyyyyn.',
  '.nnyyyyyynn.',
  '..nnnnnnnn..',
  '...aaaaaa...',
];

const CURRY = [
  '..s..s......',
  '...s..s.....',
  '.mmmmmmmmmm.',
  'moootooogoom',
  'mootoogoootm',
  'mgoooootooom',
  '.mooooooooo.',
  '.mmoooooomm.',
  '..mmmmmmmm..',
];

export const FOOD_SPRITES: Record<string, SpriteDef> = {
  idli: {
    rows: [
      '....wwww....',
      '..wwwwwwww..',
      '.wwwwswwwwq.',
      '.wswwwwwwqs.',
      '.wwwwwwwqss.',
      '..qqqqqsss..',
      '.gggggggggg.',
      'gvgggggggvgg',
    ],
  },
  egg: {
    rows: [
      '....wwww....',
      '..wwwwwwww..',
      '.wwwwjjwwwq.',
      '.wwwjyyjwwq.',
      '.wwjyyyyjwq.',
      '.wwjyyyyjwq.',
      '.wwwjyyjwwq.',
      '.wwwwjjwwqs.',
      '..wwwwwwqs..',
      '...qqqqss...',
    ],
  },
  banana: {
    rows: [
      '..........nn',
      '.........yyn',
      '........yhyy',
      '.......yhyya',
      '......yhyyya',
      '.y...yhyyyaa',
      'yyy.yhyyyaa.',
      'yyyyhyyyaa..',
      '.yyyyyyaa...',
      '..aaaaaa....',
    ],
  },
  poha: {
    rows: [
      '....yhyy....',
      '..yyhyyyyy..',
      '.yhyyoyyhyy.',
      '.yyyygyyyyy.',
      'yyoyyyyhygyy',
      'yyyhyyyyoyyy',
      'wwwwwwwwwwww',
      '.ssssssssss.',
    ],
  },
  pongal: {
    rows: [
      '...qqhqq....',
      '..qqhqqqqq..',
      '.qqqqjjqqqq.',
      '.qqkqqjqkqq.',
      '.qqqqqqqqqq.',
      'aaaaaaaaaaaa',
      '.annnnnnnna.',
      '..aaaaaaaa..',
    ],
  },
  kichadi: {
    rows: [
      '..tttttttt..',
      '.tatotatgtt.',
      '.ttgttattot.',
      '.tttatotttt.',
      '.ttotatgttt.',
      '..tttttttt..',
      '.bbbbbbbbbb.',
      '..bbbbbbbb..',
    ],
  },
  rice: {
    rows: [
      '....wwww....',
      '..wwwwwwww..',
      '.wwwwswwwwq.',
      '.wswwwwwwqs.',
      'wwwwwwwwwqss',
      '.qqqqqqqqss.',
      'ssssssssssss',
      '.zzzzzzzzzz.',
    ],
  },
  pulao: { rows: PULAO },
  friedrice: { rows: PULAO, swap: { h: 't', a: 'n', o: 'r', g: 'l' } },
  biryani: { rows: PULAO, swap: { h: 'o', a: 'u', g: 'l', o: 'y' } },
  curdrice: {
    rows: [
      '....wwww....',
      '..wwwwwwww..',
      '.wwkwwwwrww.',
      '.wwwwwgwwws.',
      'wwrwwwwwkwws',
      'wwwwkwwwwwss',
      '.nnnnnnnnnn.',
      '..nnnnnnnn..',
    ],
  },
  rasam: { rows: RASAM },
  rasamPepper: { rows: RASAM, swap: { r: 'm', o: 'n' } },
  rasamGarlic: { rows: RASAM, swap: { r: 'a', o: 'j' } },
  buttermilk: {
    rows: [
      '...g..g.....',
      '..wwwwwwww..',
      '..wqqqqqqw..',
      '..wqhqqqqw..',
      '..wqqqqqqw..',
      '..wqqqqqsw..',
      '...wqqqqw...',
      '...wwwwww...',
    ],
  },
  milk: {
    rows: [
      '..cccccccc..',
      '..cwwwwwwc..',
      '..cwwwwwwc..',
      '..cwwwwwwc..',
      '..cwwwwwwc..',
      '..cwwwwwsc..',
      '...cwwwwc...',
      '...cccccc...',
    ],
  },
  poriyal: {
    rows: [
      '.tt.tt..g...',
      'tqtttqtt.gg.',
      'tttatttatt..',
      '.eeeeeeeeee.',
      'eeeeeeeeeeee',
      '.eeeeeeeeee.',
      '..eeeeeeee..',
    ],
  },
  dal: { rows: DAL },
  kootu: { rows: DAL, swap: { y: 'g', j: 'x', r: 'o' } },
  chips: {
    rows: [
      '.b.b.b.b.b.b',
      'bbbbbbbbbbbb',
      'bbjjjjjjjjbb',
      'bbjyyyyyyjbb',
      'bbjyoyyoyjbb',
      'bbjjjjjjjjbb',
      'bbbbbbbbbbbb',
      '.bbbbbbbbbb.',
    ],
  },
  mutter: { rows: CURRY },
  chenna: { rows: CURRY, swap: { o: 'r', t: 'w' } },
  fruit: {
    rows: [
      '.....n.g....',
      '....nggg....',
      '..rrrnrrr...',
      '.rrhrrrrrr..',
      'rrhrrrrrrru.',
      'rrrrrrrrrru.',
      'rrrrrrrrruu.',
      '.rrrrrrrruu.',
      '..rrrrrruu..',
      '...uuuuuu...',
    ],
  },
  icecream: {
    rows: [
      '.....r......',
      '...iiiiii...',
      '..iihiiiii..',
      '..iiiiiiii..',
      '..wwwwwwww..',
      '.wwhwwwwwws.',
      '..tttttttt..',
      '...tatatat..',
      '....tatat...',
      '.....tat....',
      '......t.....',
    ],
  },
  corn: {
    rows: [
      '....jyj.....',
      '...jyjyj....',
      '..jyjyjyj...',
      '..yjyjyjy...',
      '..jyjyjyj...',
      '..yjyjyjy...',
      '..gjyjyjg...',
      '...ggyygg...',
      '....gggg....',
      '.....nn.....',
    ],
  },
  pavbhaji: {
    rows: [
      '...yyy......',
      '..rryrr.tt..',
      '.rrorrrrttt.',
      '.rrrorrrttt.',
      'rrorrrrr.tt.',
      '.rrrrrrr....',
      'wwwwwwwwwwww',
      '.ssssssssss.',
    ],
  },
  sundal: {
    rows: [
      '..tt.tt.tt..',
      '.tttatttatt.',
      '.tatttgttat.',
      '..tttwwttt..',
      '.gggggggggg.',
      '..gvgggggg..',
    ],
  },
  puff: {
    rows: [
      '.aajjjjjjaa.',
      'ajhhjjjjjjja',
      'ajhjjajjjjja',
      'ajjjjjjajjja',
      'ajjajjjjjjja',
      'ajjjjjjjhjja',
      'ajjjjajjjjja',
      '.aajjjjjjaa.',
      '..aaaaaaaa..',
    ],
  },
  biscuit: {
    rows: [
      '...tttttt...',
      '..tthtttta..',
      '.tthmtmtmta.',
      '.ttttttttta.',
      '.tmtmtmtmta.',
      '.ttttttttta.',
      '.tmtmtmtmta.',
      '..ttttttaa..',
      '...aaaaaa...',
    ],
  },
  bun: {
    rows: [
      '....aaaa....',
      '..aajjjjaa..',
      '.ajjhhjjjja.',
      '.ajjjjjjjja.',
      'ajwwwwwwwwja',
      'ajjjjjjjjjja',
      '.aajjjjjjaa.',
      '..nnnnnnnn..',
    ],
  },
  cake: {
    rows: [
      '.....r......',
      '....rr......',
      '..wwwwwwww..',
      '.wwiiwwiiww.',
      '.wwwwwwwwws.',
      '.nnnnnnnnnn.',
      '.iiiiiiiiii.',
      '.nnnnnnnnnn.',
      '.mmmmmmmmmm.',
    ],
  },
  maggi: {
    rows: [
      '.y.y.y.y.y.y',
      'yyyyyyyyyyyy',
      'yrrrrrrrrrry',
      'yrwrwrwrwrry',
      'yrrwrwrwrrry',
      'yrrrrrrrrrry',
      'yyyyyyyyyyyy',
      '.y.y.y.y.y.y',
    ],
  },
};
