// GENERATED by `npm run build:api` from server/ - do not edit by hand.
import { createHash, createHmac, createPublicKey, randomBytes, timingSafeEqual, verify } from "node:crypto";
//#region src/core/clock.ts
/** Date helpers. All "game days" roll over at midnight India time (IST, UTC+5:30). */
var IST_OFFSET_MS = 198e5;
var DAY_MS = 864e5;
function istDateKey(nowMs) {
	return new Date(nowMs + IST_OFFSET_MS).toISOString().slice(0, 10);
}
/** 0 = Sunday ... 6 = Saturday, for a YYYY-MM-DD key. */
function weekdayOf(dateKey) {
	return (/* @__PURE__ */ new Date(`${dateKey}T00:00:00Z`)).getUTCDay();
}
function daysBetween(a, b) {
	return Math.round((Date.parse(`${b}T00:00:00Z`) - Date.parse(`${a}T00:00:00Z`)) / DAY_MS);
}
var NICK_RE = /^[A-Za-z0-9_-]{3,14}$/;
function nicknameProblem(name) {
	if (name.length < 3 || name.length > 14) return `Use 3-14 characters.`;
	if (!NICK_RE.test(name)) return "Letters, numbers, _ and - only.";
	return null;
}
var ADJ = [
	"Spicy",
	"Sleepy",
	"Soggy",
	"Crispy",
	"Hungry",
	"Salty",
	"Saucy",
	"Lazy",
	"Cranky",
	"Sneaky",
	"Tangy",
	"Grumpy",
	"Zesty",
	"Mighty",
	"Fluffy",
	"Hasty",
	"Jolly",
	"Rusty",
	"Toasty",
	"Sly"
];
var NOUN = [
	"Idli",
	"Dosa",
	"Egg",
	"Rasam",
	"Chai",
	"Puff",
	"Rice",
	"Banana",
	"Curd",
	"Vada",
	"Poha",
	"Pongal",
	"Sambar",
	"Lassi",
	"Kurma",
	"Upma",
	"Bonda",
	"Halwa",
	"Kesari",
	"Pulao"
];
/** About 360,000 combinations; the server still checks each one is free before handing it out. */
function randomNickname(rand = Math.random) {
	const r = (n) => Math.floor(rand() * n);
	return `${ADJ[r(ADJ.length)]}${NOUN[r(NOUN.length)]}${100 + r(900)}`.slice(0, 14);
}
var emptyStreak = () => ({
	current: 0,
	best: 0,
	freezes: 0,
	lastPlayed: null,
	usedFreezeOn: null
});
/** What would happen if the player showed up on `today`? */
function streakStatus(s, today) {
	if (!s.lastPlayed) return "new";
	const gap = daysBetween(s.lastPlayed, today);
	if (gap <= 0) return "played-today";
	if (gap === 1) return "alive";
	if (gap === 2 && s.freezes > 0) return "saved-by-freeze";
	return "broken";
}
/** Streak number to *display* today (drops to 0 once it can no longer be saved). */
function displayStreak(s, today) {
	return streakStatus(s, today) === "broken" ? 0 : s.current;
}
function recordDailyPlay(s, today) {
	const status = streakStatus(s, today);
	if (status === "played-today") return s;
	const next = {
		...s,
		lastPlayed: today
	};
	if (status === "alive" || status === "saved-by-freeze") {
		if (status === "saved-by-freeze") {
			next.freezes -= 1;
			next.usedFreezeOn = today;
		}
		next.current = s.current + 1;
	} else next.current = 1;
	if (next.current % 7 === 0) next.freezes = Math.min(2, next.freezes + 1);
	next.best = Math.max(s.best, next.current);
	return next;
}
var DT = 1 / 60;
var PLAYER_SPEED = 5.8;
var COURSE_COUNT = 3;
var POINTS = {
	food: 10,
	snack: 100,
	enemyBase: 200,
	stageClear: 500,
	perStomach: 100,
	perSecondUnderPar: 5
};
var COMBO_WINDOW = 2.2;
var HUNGER_REFILL = .045;
var INVULN_SECONDS = 2.2;
/** Monday = tier 0 (easiest) ... Sunday = tier 6 (hardest). */
function tierOf(weekday) {
	return (weekday + 6) % 7;
}
//#endregion
//#region src/game/difficulty.ts
/** Static difficulty curve (by weekday + course) and the adaptive player-skill model. */
var LEVEL_IDS = [
	"easy",
	"normal",
	"hard"
];
var LEVELS = {
	easy: {
		label: "EASY",
		blurb: "Slower dishes, fewer dishes to eat, 4 stomachs, longer Maggi, no boss. Score x0.6.",
		speed: .72,
		release: 1.6,
		hunger: 1.3,
		food: -2,
		maggi: 2,
		stomachs: 4,
		cap: .9,
		score: .6
	},
	normal: {
		label: "NORMAL",
		blurb: "The intended recipe. Score x1.",
		speed: 1,
		release: 1,
		hunger: 1,
		food: 0,
		maggi: 0,
		stomachs: 3,
		cap: .9,
		score: 1
	},
	hard: {
		label: "HARD",
		blurb: "Faster dishes, more dishes to eat, quicker releases, shorter Maggi, hungrier you. Score x1.2.",
		speed: 1.08,
		release: .75,
		hunger: .8,
		food: 2,
		maggi: -1.5,
		stomachs: 3,
		cap: .96,
		score: 1.2
	}
};
function stageDifficulty(weekday, course, adaptive = 1, level = "normal") {
	const L = LEVELS[level];
	const tier = tierOf(weekday);
	const roster = ["blob", "chapati"];
	if (tier >= 1 || course >= 2 || level === "hard") roster.push("curry");
	if (tier >= 2 || tier >= 1 && course >= 1 || level === "hard" && course >= 1) roster.push("special");
	if (level === "easy" && roster.length > 3) roster.pop();
	const base = .48 + .018 * tier + .013 * course;
	return {
		tier,
		course,
		roster,
		enemySpeedRatio: Math.min(L.cap, base * adaptive * L.speed),
		releaseInterval: Math.max(1.2, (3.6 - .25 * tier - .2 * course) * L.release),
		foodCount: 12 + course + Math.floor(tier / 2) + L.food,
		maggiSeconds: Math.max(3.5, 7 - .2 * tier + L.maggi),
		hungerSeconds: 100 * L.hunger,
		parTime: 45 + course * 3
	};
}
//#endregion
//#region src/core/rng.ts
/** mulberry32: tiny, fast, good-enough PRNG. */
function mulberry32(seed) {
	let a = seed >>> 0;
	return () => {
		a = a + 1831565813 >>> 0;
		let t = a;
		t = Math.imul(t ^ t >>> 15, t | 1);
		t ^= t + Math.imul(t ^ t >>> 7, t | 61);
		return ((t ^ t >>> 14) >>> 0) / 4294967296;
	};
}
/** FNV-1a string hash -> 32-bit seed. */
function hashString(s) {
	let h = 2166136261;
	for (let i = 0; i < s.length; i++) {
		h ^= s.charCodeAt(i);
		h = Math.imul(h, 16777619);
	}
	return h >>> 0;
}
function randInt(rng, n) {
	return Math.floor(rng() * n);
}
/** In-place Fisher-Yates. */
function shuffle(arr, rng) {
	for (let i = arr.length - 1; i > 0; i--) {
		const j = randInt(rng, i + 1);
		const tmp = arr[i];
		arr[i] = arr[j];
		arr[j] = tmp;
	}
	return arr;
}
//#endregion
//#region src/game/perks.ts
/** Between-stage upgrades ("roguelite" layer that makes each run feel different). */
var freshModifiers = () => ({
	speedMul: 1,
	maggiBonus: 0,
	comboBonus: 0,
	showPaths: false,
	extraStomachs: 0
});
var PERKS = [
	{
		id: "chew",
		name: "Fast Chewing",
		desc: "+8% move speed",
		apply: (m) => void (m.speedMul *= 1.08)
	},
	{
		id: "stomach",
		name: "Extra Stomach",
		desc: "+1 stomach (life)",
		apply: (m) => void (m.extraStomachs += 1)
	},
	{
		id: "maggi",
		name: "Iron Stomach",
		desc: "Maggi lasts +3 seconds",
		apply: (m) => void (m.maggiBonus += 3)
	},
	{
		id: "spoon",
		name: "Lucky Spoon",
		desc: "Combo window +1 second",
		apply: (m) => void (m.comboBonus += 1)
	},
	{
		id: "hack",
		name: "Hostel Hack",
		desc: "See enemy paths",
		apply: (m) => void (m.showPaths = true)
	}
];
function offerPerks(rng, owned) {
	return shuffle([...PERKS.filter((p) => !owned.has(p.id) || p.id === "stomach" || p.id === "chew")], rng).slice(0, 3);
}
//#endregion
//#region src/core/types.ts
/** Direction index: 0 up, 1 right, 2 down, 3 left. */
var DX = [
	0,
	1,
	0,
	-1
];
var DY = [
	-1,
	0,
	1,
	0
];
var NO_DIR = {
	dx: 0,
	dy: 0
};
var DIR_LIST = [
	{
		dx: 0,
		dy: -1
	},
	{
		dx: 1,
		dy: 0
	},
	{
		dx: 0,
		dy: 1
	},
	{
		dx: -1,
		dy: 0
	}
];
function dirFromCode(code) {
	return code === 0 ? NO_DIR : DIR_LIST[code - 1];
}
//#endregion
//#region src/core/heap.ts
/**
* Binary min-heap backed by typed arrays with a fixed capacity.
* Used as the A* / Dijkstra open set. Pre-allocated so searches allocate nothing.
*/
var MinHeap = class {
	keys;
	vals;
	size = 0;
	constructor(capacity) {
		this.keys = new Float64Array(capacity);
		this.vals = new Int32Array(capacity);
	}
	get isEmpty() {
		return this.size === 0;
	}
	clear() {
		this.size = 0;
	}
	push(key, val) {
		if (this.size >= this.keys.length) return;
		let i = this.size++;
		while (i > 0) {
			const parent = i - 1 >> 1;
			if (this.keys[parent] <= key) break;
			this.keys[i] = this.keys[parent];
			this.vals[i] = this.vals[parent];
			i = parent;
		}
		this.keys[i] = key;
		this.vals[i] = val;
	}
	/** Removes and returns the value with the smallest key. */
	pop() {
		const top = this.vals[0];
		const n = --this.size;
		if (n > 0) {
			const key = this.keys[n];
			const val = this.vals[n];
			let i = 0;
			for (;;) {
				let child = 2 * i + 1;
				if (child >= n) break;
				if (child + 1 < n && this.keys[child + 1] < this.keys[child]) child++;
				if (this.keys[child] >= key) break;
				this.keys[i] = this.keys[child];
				this.vals[i] = this.vals[child];
				i = child;
			}
			this.keys[i] = key;
			this.vals[i] = val;
		}
		return top;
	}
};
//#endregion
//#region src/game/pathfinding.ts
/**
* Grid search algorithms: A*, Dijkstra and BFS share one allocation-free Pathfinder.
* Buffers are reused between searches via a generation "stamp", so enemy AI can
* search every time it reaches a tile without creating garbage.
*/
var Pathfinder = class {
	grid;
	n;
	g;
	parent;
	seen;
	closed;
	queue;
	heap;
	stamp = 0;
	/** Nodes expanded by the most recent search. */
	expanded = 0;
	constructor(grid) {
		this.grid = grid;
		this.n = grid.cols * grid.rows;
		this.g = new Int32Array(this.n);
		this.parent = new Int32Array(this.n);
		this.seen = new Uint32Array(this.n);
		this.closed = new Uint32Array(this.n);
		this.queue = new Int32Array(this.n);
		this.heap = new MinHeap(this.n * 4 + 16);
	}
	/** Runs a search; `blocked` is one extra tile treated as a wall (used to forbid reversing). */
	run(algo, start, goal, blocked) {
		const { cols, rows, walls } = this.grid;
		const stamp = ++this.stamp;
		this.expanded = 0;
		this.seen[start] = stamp;
		this.g[start] = 0;
		this.parent[start] = -1;
		if (algo === "bfs") {
			let head = 0;
			let tail = 0;
			this.queue[tail++] = start;
			while (head < tail) {
				const cur = this.queue[head++];
				this.expanded++;
				if (cur === goal) return true;
				const cx = cur % cols;
				const cy = cur / cols | 0;
				for (let d = 0; d < 4; d++) {
					const nx = cx + DX[d];
					const ny = cy + DY[d];
					if (nx < 0 || ny < 0 || nx >= cols || ny >= rows) continue;
					const ni = ny * cols + nx;
					if (walls[ni] || ni === blocked || this.seen[ni] === stamp) continue;
					this.seen[ni] = stamp;
					this.parent[ni] = cur;
					this.queue[tail++] = ni;
				}
			}
			return false;
		}
		const useH = algo === "astar";
		const gx = goal % cols;
		const gy = goal / cols | 0;
		const heap = this.heap;
		heap.clear();
		heap.push(0, start);
		while (!heap.isEmpty) {
			const cur = heap.pop();
			if (this.closed[cur] === stamp) continue;
			this.closed[cur] = stamp;
			this.expanded++;
			if (cur === goal) return true;
			const cx = cur % cols;
			const cy = cur / cols | 0;
			const ng = this.g[cur] + 1;
			for (let d = 0; d < 4; d++) {
				const nx = cx + DX[d];
				const ny = cy + DY[d];
				if (nx < 0 || ny < 0 || nx >= cols || ny >= rows) continue;
				const ni = ny * cols + nx;
				if (walls[ni] || ni === blocked || this.closed[ni] === stamp) continue;
				if (this.seen[ni] !== stamp || ng < this.g[ni]) {
					this.seen[ni] = stamp;
					this.g[ni] = ng;
					this.parent[ni] = cur;
					heap.push(useH ? ng + Math.abs(nx - gx) + Math.abs(ny - gy) : ng, ni);
				}
			}
		}
		return false;
	}
	search(algo, start, goal, blocked = -1) {
		const found = start === goal ? true : this.run(algo, start, goal, blocked);
		const path = [];
		if (found && start !== goal) {
			for (let c = goal; c !== start && c >= 0; c = this.parent[c]) path.push(c);
			path.reverse();
		}
		return {
			found,
			path,
			expanded: this.expanded
		};
	}
	/** First tile on the A* path from `start` to `goal`, or -1. Allocation-free hot path for enemy AI. */
	nextStep(start, goal, blocked = -1) {
		if (start === goal || !this.run("astar", start, goal, blocked)) return -1;
		let c = goal;
		while (this.parent[c] !== start) c = this.parent[c];
		return c;
	}
};
/** BFS distance from `start` to every reachable floor tile (-1 = unreachable/wall). */
function bfsDistances(grid, start) {
	const { cols, rows, walls } = grid;
	const dist = new Int32Array(cols * rows).fill(-1);
	const queue = new Int32Array(cols * rows);
	let head = 0;
	let tail = 0;
	dist[start] = 0;
	queue[tail++] = start;
	while (head < tail) {
		const cur = queue[head++];
		const cx = cur % cols;
		const cy = cur / cols | 0;
		for (let d = 0; d < 4; d++) {
			const nx = cx + DX[d];
			const ny = cy + DY[d];
			if (nx < 0 || ny < 0 || nx >= cols || ny >= rows) continue;
			const ni = ny * cols + nx;
			if (walls[ni] || dist[ni] !== -1) continue;
			dist[ni] = dist[cur] + 1;
			queue[tail++] = ni;
		}
	}
	return dist;
}
//#endregion
//#region src/game/furniture.ts
/**
* Procedural dining-hall layout. Instead of carving corridors, we *furnish* the room: sets of tables
* with chairs, stools, booths, buffet counters and planters are dropped onto the floor one at a time.
* The walls the player and enemies bump into are simply the footprints of that furniture.
*
* Constraint-based placement (a small constraint-satisfaction / rejection-sampling generator):
*   1. every piece must fit inside the room and stay clear of the kitchen, the start and the corners;
*   2. pieces keep at least one empty tile between them (the aisles) unless they are flush against a wall;
*   3. a piece is rejected if it would cut the floor into disconnected islands (checked with BFS).
* Everything derives from the seeded RNG, so a date always gives the same hall.
*/
var TEMPLATES = [
	{
		name: "two-top",
		rows: [
			" c ",
			"cTc",
			" c "
		],
		weight: 4
	},
	{
		name: "pair",
		rows: [
			"cc",
			"TT",
			"cc"
		],
		weight: 5
	},
	{
		name: "family",
		rows: [
			"ccc",
			"TTT",
			"TTT",
			"ccc"
		],
		weight: 3
	},
	{
		name: "long",
		rows: [
			"cccc",
			"TTTT",
			"cccc"
		],
		weight: 3
	},
	{
		name: "round",
		rows: [
			" ss ",
			"sRRs",
			"sRRs",
			" ss "
		],
		weight: 4
	},
	{
		name: "big",
		rows: [
			" cc ",
			"cTTc",
			"cTTc",
			" cc "
		],
		weight: 2
	},
	{
		name: "diner",
		rows: [
			"cT",
			"cT",
			"cT"
		],
		weight: 2
	},
	{
		name: "booth",
		rows: [
			"bTT",
			"bTT",
			"bTT"
		],
		weight: 5,
		wall: true
	},
	{
		name: "booth-short",
		rows: ["bT", "bT"],
		weight: 3,
		wall: true
	},
	{
		name: "buffet",
		rows: ["FFF"],
		weight: 2
	},
	{
		name: "buffet-long",
		rows: ["FFFF"],
		weight: 1
	},
	{
		name: "small-table",
		rows: ["T"],
		weight: 3
	},
	{
		name: "stool",
		rows: ["s"],
		weight: 1
	},
	{
		name: "planter",
		rows: ["P"],
		weight: 2
	},
	{
		name: "crate",
		rows: ["X"],
		weight: 2
	}
];
var inRoom = (x, y) => x >= 1 && y >= 1 && x <= 17 && y <= 19;
/** Tiles that must stay open: the kitchen where dishes spawn, the start, and the four corners. */
function reservedTiles() {
	const out = /* @__PURE__ */ new Set();
	const add = (x0, y0, x1, y1) => {
		for (let y = y0; y <= y1; y++) for (let x = x0; x <= x1; x++) out.add(y * 19 + x);
	};
	add(6, 7, 12, 11);
	add(7, 17, 11, 19);
	add(1, 1, 2, 2);
	add(16, 1, 17, 2);
	add(1, 18, 2, 19);
	add(16, 18, 17, 19);
	return out;
}
function transpose(rows) {
	const out = [];
	for (let x = 0; x < rows[0].length; x++) out.push(rows.map((r) => r[x]).join(""));
	return out;
}
var flipX = (rows) => rows.map((r) => [...r].reverse().join(""));
var flipY = (rows) => [...rows].reverse();
var DIRS = [
	[
		0,
		-1,
		"n"
	],
	[
		1,
		0,
		"e"
	],
	[
		0,
		1,
		"s"
	],
	[
		-1,
		0,
		"w"
	]
];
/** Turn a template placed at (ox, oy) into pieces (merging table cells into one rectangle). */
function piecesOf(rows, ox, oy, set, rng) {
	const out = [];
	const at = (x, y) => rows[y] && rows[y][x] || " ";
	const isTable = (c) => c === "T" || c === "R" || c === "F";
	for (const glyph of [
		"T",
		"R",
		"F"
	]) {
		let x0 = 99, y0 = 99, x1 = -1, y1 = -1;
		for (let y = 0; y < rows.length; y++) for (let x = 0; x < rows[y].length; x++) {
			if (rows[y][x] !== glyph) continue;
			x0 = Math.min(x0, x);
			y0 = Math.min(y0, y);
			x1 = Math.max(x1, x);
			y1 = Math.max(y1, y);
		}
		if (x1 < 0) continue;
		const kind = glyph === "T" ? "table" : glyph === "R" ? "round" : "counter";
		out.push({
			kind,
			x: ox + x0,
			y: oy + y0,
			w: x1 - x0 + 1,
			h: y1 - y0 + 1,
			set
		});
	}
	for (let y = 0; y < rows.length; y++) for (let x = 0; x < rows[y].length; x++) {
		const c = rows[y][x];
		if (c === " " || isTable(c)) continue;
		const kind = c === "c" ? "chair" : c === "s" ? "stool" : c === "b" ? "bench" : c === "P" ? "planter" : "crate";
		let facing;
		if (kind === "chair" || kind === "stool" || kind === "bench") {
			for (const [dx, dy, f] of DIRS) if (isTable(at(x + dx, y + dy))) facing = f;
			facing ??= DIRS[randInt(rng, 4)][2];
		}
		const piece = {
			kind,
			x: ox + x,
			y: oy + y,
			w: 1,
			h: 1,
			set
		};
		if (facing) piece.facing = facing;
		out.push(piece);
	}
	return mergeBenches(out);
}
function mergeBenches(pieces) {
	const benches = pieces.filter((p) => p.kind === "bench").sort((a, b) => a.y - b.y || a.x - b.x);
	const rest = pieces.filter((p) => p.kind !== "bench");
	const merged = [];
	for (const b of benches) {
		const prev = merged[merged.length - 1];
		if (prev && prev.x === b.x && prev.w === b.w && prev.y + prev.h === b.y && prev.facing === b.facing) prev.h += 1;
		else merged.push({ ...b });
	}
	return [...rest, ...merged];
}
/** Paint the pieces' footprints into a wall mask (border walls included). */
function wallsFromPieces(pieces) {
	const walls = /* @__PURE__ */ new Uint8Array(399);
	for (let y = 0; y < 21; y++) for (let x = 0; x < 19; x++) if (!inRoom(x, y)) walls[y * 19 + x] = 1;
	for (const p of pieces) for (let y = p.y; y < p.y + p.h; y++) for (let x = p.x; x < p.x + p.w; x++) walls[y * 19 + x] = 1;
	return walls;
}
/** Flood fill from the start: true when every open tile can be reached. */
function connected(walls, from) {
	const seen = new Uint8Array(walls.length);
	const stack = [from];
	seen[from] = 1;
	let reached = 0;
	while (stack.length) {
		const t = stack.pop();
		reached++;
		const x = t % 19;
		const y = t / 19 | 0;
		for (const [dx, dy] of DIRS) {
			const nx = x + dx;
			const ny = y + dy;
			if (nx < 0 || ny < 0 || nx >= 19 || ny >= 21) continue;
			const n = ny * 19 + nx;
			if (walls[n] || seen[n]) continue;
			seen[n] = 1;
			stack.push(n);
		}
	}
	let open = 0;
	for (let i = 0; i < walls.length; i++) if (!walls[i]) open++;
	return reached === open;
}
function pickTemplate(rng) {
	const total = TEMPLATES.reduce((s, t) => s + t.weight, 0);
	let r = rng() * total;
	for (const t of TEMPLATES) {
		r -= t.weight;
		if (r <= 0) return t;
	}
	return TEMPLATES[0];
}
/** Fraction of the room's tiles that should end up covered by furniture. */
var TARGET_FILL = .32;
/** Chance that a set may be pushed right up against its neighbours (aisles then come from the BFS rule). */
var TOUCH_CHANCE = .4;
var START = 370;
function furnishOnce(rng) {
	const reserved = reservedTiles();
	const pieces = [];
	const solid = /* @__PURE__ */ new Uint8Array(399);
	let covered = 0;
	const room = 323;
	let set = 0;
	for (let attempt = 0; attempt < 1500 && covered / room < TARGET_FILL; attempt++) {
		const t = pickTemplate(rng);
		let rows = t.rows;
		if (!t.fixed && rng() < .5) rows = transpose(rows);
		if (rng() < .5) rows = flipX(rows);
		if (rng() < .5) rows = flipY(rows);
		const h = rows.length;
		const w = rows[0].length;
		let ox;
		if (t.wall) {
			const left = rng() < .5;
			const benchOnLeft = rows.every((r) => r[0] === "b");
			const benchOnRight = rows.every((r) => r[w - 1] === "b");
			if (left && !benchOnLeft) rows = flipX(rows);
			if (!left && !benchOnRight) rows = flipX(rows);
			ox = left ? 1 : 18 - w;
		} else ox = 1 + randInt(rng, 17 - w + 1);
		const oy = 1 + randInt(rng, 19 - h + 1);
		const touch = rng() < TOUCH_CHANCE;
		const cells = [];
		let ok = true;
		for (let y = 0; y < h && ok; y++) for (let x = 0; x < w && ok; x++) {
			if (rows[y][x] === " ") continue;
			const gx = ox + x;
			const gy = oy + y;
			const tile = gy * 19 + gx;
			if (!inRoom(gx, gy) || reserved.has(tile)) {
				ok = false;
				break;
			}
			if (solid[tile]) {
				ok = false;
				break;
			}
			for (let dy = -1; dy <= 1 && ok && !touch; dy++) for (let dx = -1; dx <= 1; dx++) {
				const nx = gx + dx;
				const ny = gy + dy;
				if (!inRoom(nx, ny)) continue;
				const n = ny * 19 + nx;
				if (solid[n] && !cellsHas(cells, n)) {
					ok = false;
					break;
				}
			}
			cells.push(tile);
		}
		if (!ok || !cells.length) continue;
		const trial = solid.slice();
		for (const c of cells) trial[c] = 1;
		const walls = new Uint8Array(trial);
		for (let i = 0; i < walls.length; i++) if (!inRoom(i % 19, i / 19 | 0)) walls[i] = 1;
		if (!connected(walls, START)) continue;
		solid.set(trial);
		covered += cells.length;
		pieces.push(...piecesOf(rows, ox, oy, set++, rng));
	}
	plugDeadEnds(pieces, reserved, rng);
	plugPockets(pieces, reserved, rng);
	return {
		walls: wallsFromPieces(pieces),
		pieces
	};
}
function cellsHas(cells, n) {
	return cells.includes(n);
}
/**
* Dead-end pockets are death traps against chasing enemies (and look like gaps in the furniture),
* so each one is plugged with something you would really find stuffed in a corner: a planter, a crate
* or a spare stool. Filling a dead end can never disconnect the floor, so the layout stays valid.
*/
function plugDeadEnds(pieces, reserved, rng) {
	const STUFF = [
		"planter",
		"crate",
		"stool",
		"crate",
		"planter"
	];
	for (let pass = 0; pass < 40; pass++) {
		const walls = wallsFromPieces(pieces);
		let plugged = 0;
		for (let y = 1; y < 20; y++) for (let x = 1; x < 18; x++) {
			const t = y * 19 + x;
			if (walls[t] || reserved.has(t)) continue;
			let open = 0;
			for (const [dx, dy] of DIRS) if (!walls[(y + dy) * 19 + x + dx]) open++;
			if (open > 1) continue;
			const kind = STUFF[randInt(rng, STUFF.length)];
			const piece = {
				kind,
				x,
				y,
				w: 1,
				h: 1,
				set: 1e3 + pieces.length
			};
			if (kind === "stool") piece.facing = DIRS[randInt(rng, 4)][2];
			pieces.push(piece);
			walls[t] = 1;
			plugged++;
		}
		if (!plugged) return;
	}
}
var POCKET_MAX = 14;
/**
* Open tiles that sit in a small cut-off pocket: removing one single tile (an "articulation" tile)
* would separate them from the start. A small room with one doorway is a trap when something is chasing you,
* so these are plugged with clutter, or the whole layout is re-rolled when the pocket holds a reserved tile.
*/
function smallPockets(walls) {
	const n = walls.length;
	const disc = new Int32Array(n).fill(-1);
	const low = new Int32Array(n);
	const parent = new Int32Array(n).fill(-1);
	const order = [];
	const iter = new Int8Array(n);
	const stack = [START];
	let time = 0;
	disc[START] = low[START] = time++;
	order.push(START);
	while (stack.length) {
		const u = stack[stack.length - 1];
		if (iter[u] < 4) {
			const [dx, dy] = DIRS[iter[u]++];
			const v = (u / 19 | 0) * 19 + u % 19 + dy * 19 + dx;
			if (walls[v]) continue;
			if (disc[v] < 0) {
				parent[v] = u;
				disc[v] = low[v] = time++;
				order.push(v);
				stack.push(v);
			} else if (v !== parent[u]) low[u] = Math.min(low[u], disc[v]);
		} else {
			stack.pop();
			const p = parent[u];
			if (p >= 0) low[p] = Math.min(low[p], low[u]);
		}
	}
	const size = new Int32Array(n);
	for (let i = order.length - 1; i >= 0; i--) {
		const u = order[i];
		size[u] += 1;
		if (parent[u] >= 0) size[parent[u]] += size[u];
	}
	const pockets = [];
	for (const c of order) {
		const u = parent[c];
		if (u < 0 || low[c] < disc[u] || size[c] > POCKET_MAX) continue;
		const start = disc[c];
		pockets.push(order.slice(start, start + size[c]));
	}
	return pockets;
}
function plugPockets(pieces, reserved, rng) {
	const STUFF = [
		"planter",
		"crate",
		"crate",
		"stool"
	];
	for (let pass = 0; pass < 12; pass++) {
		const pockets = smallPockets(wallsFromPieces(pieces)).filter((c) => !c.some((t) => reserved.has(t)));
		if (!pockets.length) return;
		for (const t of new Set(pockets.flat())) {
			const piece = {
				kind: STUFF[randInt(rng, STUFF.length)],
				x: t % 19,
				y: t / 19 | 0,
				w: 1,
				h: 1,
				set: 2e3 + pieces.length
			};
			if (piece.kind === "stool") piece.facing = DIRS[randInt(rng, 4)][2];
			pieces.push(piece);
		}
	}
}
/** Furnish the hall; re-rolls (deterministically, from the same RNG stream) until no trap pockets remain. */
function furnishHall(rng) {
	let best = null;
	let bestScore = Infinity;
	for (let i = 0; i < 80; i++) {
		const layout = furnishOnce(rng);
		const score = smallPockets(layout.walls).reduce((n, c) => n + c.length, 0);
		if (score < bestScore) {
			best = layout;
			bestScore = score;
		}
		if (score === 0) break;
	}
	return best;
}
//#endregion
//#region src/game/maze.ts
/**
* Procedural content generation: the dining hall is furnished with tables, chairs and booths
* (see furniture.ts), then populated with an exit, power-ups and food.
* Everything derives from one seed, so a given date gives every player the same hall.
*/
var idx = (x, y) => y * 19 + x;
var xOf = (i) => i % 19;
var yOf = (i) => i / 19 | 0;
var manhattan = (a, b) => Math.abs(xOf(a) - xOf(b)) + Math.abs(yOf(a) - yOf(b));
var START_TILE = idx(9, 19);
var DEN_TILES = [
	idx(9, 9),
	idx(7, 9),
	idx(11, 9),
	idx(9, 7)
];
var PATROL_TILES = [
	idx(1, 1),
	idx(17, 1),
	idx(17, 19),
	idx(1, 19)
];
var MIN_EXIT_DISTANCE = 22;
/**
* Step 2: place gameplay objects. Deterministic for a given seed + parameters.
* If a generated maze happens to put the exit too close to the start, it is re-rolled
* from a derived seed (still deterministic), so every level is a real trek.
*/
function buildLayout(seed, opts) {
	let best = null;
	let bestDist = -1;
	for (let attempt = 0; attempt < 12; attempt++) {
		const layout = populate(mulberry32(seed + Math.imul(attempt, 2654435761) >>> 0), opts);
		const d = bfsDistances(layout.grid, layout.start)[layout.exit];
		if (d > bestDist) {
			best = layout;
			bestDist = d;
		}
		if (d >= MIN_EXIT_DISTANCE) break;
	}
	return best;
}
function populate(rng, opts) {
	const hall = furnishHall(rng);
	const grid = {
		cols: 19,
		rows: 21,
		walls: hall.walls
	};
	const floor = [];
	for (let i = 0; i < 399; i++) if (!grid.walls[i]) floor.push(i);
	const distStart = bfsDistances(grid, START_TILE);
	const distDen = bfsDistances(grid, DEN_TILES[0]);
	const taken = /* @__PURE__ */ new Set([START_TILE, ...DEN_TILES]);
	const byFar = (list) => [...list].sort((a, b) => distStart[b] - distStart[a]);
	const ranked = byFar(floor.filter((t) => !taken.has(t)));
	const far = ranked.filter((t) => distStart[t] >= distStart[ranked[0]] * .88);
	const exit = far[randInt(rng, far.length)];
	taken.add(exit);
	const maggi = [];
	for (const t of shuffle([...floor], rng)) {
		if (maggi.length >= opts.maggiCount) break;
		if (taken.has(t) || distStart[t] < 9 || manhattan(t, exit) < 7) continue;
		if (maggi.some((m) => manhattan(m, t) < 9)) continue;
		maggi.push(t);
		taken.add(t);
	}
	const nearDen = floor.filter((t) => !taken.has(t) && distDen[t] >= 3 && distDen[t] <= 6);
	const snack = nearDen.length ? nearDen[randInt(rng, nearDen.length)] : floor.find((t) => !taken.has(t));
	taken.add(snack);
	const food = [];
	const candidates = shuffle(floor.filter((t) => !taken.has(t) && manhattan(t, START_TILE) > 2), rng);
	for (let gap = 3; gap >= 1 && food.length < opts.foodCount; gap--) for (const t of candidates) {
		if (food.length >= opts.foodCount) break;
		if (food.some((f) => f.tile === t) || food.some((f) => manhattan(f.tile, t) < gap)) continue;
		food.push({
			tile: t,
			item: opts.items[randInt(rng, opts.items.length)]
		});
	}
	return {
		grid,
		furniture: hall.pieces,
		floor,
		start: START_TILE,
		exit,
		maggi,
		snack,
		food
	};
}
//#endregion
//#region src/game/mover.ts
function makeMover(col, row, speed) {
	return {
		col,
		row,
		dx: 0,
		dy: 0,
		t: 0,
		speed
	};
}
var moverX = (m) => m.col + m.dx * m.t;
var moverY = (m) => m.row + m.dy * m.t;
/** Turn around in place (legal at any moment, like Pac-Man). */
function reverseMover(m) {
	if (m.dx === 0 && m.dy === 0) return;
	m.col += m.dx;
	m.row += m.dy;
	m.t = 1 - m.t;
	m.dx = -m.dx;
	m.dy = -m.dy;
}
/**
* Advances a mover by `dt`. `decide` is called whenever the mover sits on a tile centre
* and must set dx/dy to a legal direction (or (0,0) to stop).
*/
function advanceMover(m, dt, decide) {
	let budget = m.speed * dt;
	let guard = 0;
	while (budget > 1e-9 && guard++ < 8) {
		if (m.dx === 0 && m.dy === 0) {
			decide(m);
			if (m.dx === 0 && m.dy === 0) return;
		}
		const need = 1 - m.t;
		if (budget >= need) {
			budget -= need;
			m.col += m.dx;
			m.row += m.dy;
			m.t = 0;
			decide(m);
			if (m.dx === 0 && m.dy === 0) return;
		} else {
			m.t += budget;
			budget = 0;
		}
	}
}
//#endregion
//#region src/game/enemies.ts
/**
* Enemy AI.
*
* Every enemy is a small finite state machine over its *mode*:
*     den -> active <-> scared -> eaten -> den
* What differs is the `active` behaviour (Strategy pattern): each kind picks a target tile,
* and A* turns that target into the next step. Decisions only happen when an enemy reaches
* a tile centre and has a real choice, which keeps the AI cheap enough for phones.
*/
function makeEnemy(id, kind, spawn, baseSpeed, releaseAt) {
	return {
		id,
		kind,
		m: makeMover(xOf(spawn), yOf(spawn), baseSpeed),
		mode: "den",
		spawn,
		releaseAt,
		scaredUntil: 0,
		baseSpeed,
		special: "patrol",
		patrolIdx: id % PATROL_TILES.length,
		chaseLostAt: -1,
		target: -1
	};
}
/** Back to the kitchen (used after the player loses a stomach). */
function resetEnemy(e, releaseAt) {
	e.m.col = xOf(e.spawn);
	e.m.row = yOf(e.spawn);
	e.m.dx = 0;
	e.m.dy = 0;
	e.m.t = 0;
	e.mode = "den";
	e.releaseAt = releaseAt;
	e.special = "patrol";
	e.chaseLostAt = -1;
}
function frighten(e, until) {
	if (e.kind === "warden" || e.mode !== "active" && e.mode !== "scared") return false;
	if (e.mode === "active") reverseMover(e.m);
	e.mode = "scared";
	e.scaredUntil = until;
	return true;
}
var chase = (_e, c) => c.pTile;
/** Aims a few tiles ahead of the player's heading; closes in directly when near. */
var ambush = (e, c) => {
	if (manhattan(e.m.row * 19 + e.m.col, c.pTile) <= 3 || c.pdx === 0 && c.pdy === 0) return c.pTile;
	const px = xOf(c.pTile);
	const py = yOf(c.pTile);
	for (let k = 4; k >= 1; k--) {
		const x = px + c.pdx * k;
		const y = py + c.pdy * k;
		if (x > 0 && y > 0 && x < c.grid.cols - 1 && y < c.grid.rows - 1 && !c.grid.walls[idx(x, y)]) return idx(x, y);
	}
	return c.pTile;
};
var wander = () => -1;
/** Wednesday Special: PATROL corners until the player gets close, then CHASE; gives up after losing sight. */
var moody = (e, c) => {
	const here = e.m.row * 19 + e.m.col;
	const d = manhattan(here, c.pTile);
	if (e.special === "patrol") {
		if (d <= 7) {
			e.special = "chase";
			e.chaseLostAt = -1;
		}
	} else if (d > 10) {
		if (e.chaseLostAt < 0) e.chaseLostAt = c.now;
		else if (c.now - e.chaseLostAt > 2.5) e.special = "patrol";
	} else e.chaseLostAt = -1;
	if (e.special === "chase") return c.pTile;
	if (manhattan(here, PATROL_TILES[e.patrolIdx]) <= 1) e.patrolIdx = (e.patrolIdx + 1) % PATROL_TILES.length;
	return PATROL_TILES[e.patrolIdx];
};
var BEHAVIOURS = {
	blob: chase,
	curry: ambush,
	chapati: wander,
	special: moody,
	warden: chase
};
var opts = /* @__PURE__ */ new Int8Array(4);
function chooseDirection(e, c) {
	const m = e.m;
	const here = m.row * 19 + m.col;
	if (e.mode === "eaten" && here === e.spawn) {
		e.mode = "den";
		e.releaseAt = c.now + 2.5;
		m.dx = 0;
		m.dy = 0;
		return;
	}
	const rev = m.dx !== 0 || m.dy !== 0 ? here - (m.dy * 19 + m.dx) : -1;
	let n = 0;
	for (let d = 0; d < 4; d++) {
		const nx = m.col + DX[d];
		const ny = m.row + DY[d];
		if (nx < 0 || ny < 0 || nx >= c.grid.cols || ny >= c.grid.rows) continue;
		const ni = ny * 19 + nx;
		if (c.grid.walls[ni] || ni === rev) continue;
		opts[n++] = d;
	}
	if (n === 0) {
		for (let d = 0; d < 4; d++) if ((m.row + DY[d]) * 19 + (m.col + DX[d]) === rev) opts[n++] = d;
	}
	if (n === 0) {
		m.dx = 0;
		m.dy = 0;
		return;
	}
	let chosen = opts[0];
	if (n > 1) {
		const target = e.mode === "eaten" ? e.spawn : e.mode === "active" ? BEHAVIOURS[e.kind](e, c) : -1;
		e.target = target;
		let found = -1;
		if (target >= 0 && target !== here) {
			const next = c.pf.nextStep(here, target, e.mode === "eaten" ? -1 : rev);
			if (next >= 0) for (let i = 0; i < n; i++) {
				const d = opts[i];
				if ((m.row + DY[d]) * 19 + (m.col + DX[d]) === next) found = d;
			}
		}
		chosen = found >= 0 ? found : opts[Math.floor(c.rng() * n)];
	} else e.target = -1;
	m.dx = DX[chosen];
	m.dy = DY[chosen];
}
function updateEnemy(e, dt, c) {
	if (e.mode === "den") {
		if (c.now < e.releaseAt) return;
		e.mode = "active";
	}
	if (e.mode === "scared" && c.now >= e.scaredUntil) e.mode = "active";
	e.m.speed = e.baseSpeed * (e.mode === "scared" ? .55 : e.mode === "eaten" ? 2 : 1);
	advanceMover(e.m, dt, () => chooseDirection(e, c));
}
//#endregion
//#region src/game/menu.ts
var I = (kind, name) => ({
	kind,
	name
});
var egg = I("egg", "Boiled Egg");
var banana = I("banana", "Banana");
var fruit = I("fruit", "Special Fruit");
var milk = I("milk", "Milk");
var buttermilk = I("buttermilk", "Butter Milk");
var MENUS = [
	{
		breakfast: [
			I("idli", "Idli"),
			egg,
			banana
		],
		lunch: [
			I("rice", "White Rice"),
			I("rasam", "Tomato Rasam"),
			buttermilk
		],
		dinner: [
			fruit,
			milk,
			I("icecream", "Ice Cream")
		],
		snack: I("corn", "Sweet Corn")
	},
	{
		breakfast: [
			I("poha", "Poha"),
			egg,
			banana
		],
		lunch: [
			I("pulao", "Variety Rice"),
			I("rasamPepper", "Pepper Rasam"),
			buttermilk
		],
		dinner: [
			I("mutter", "Aloo Mutter"),
			fruit,
			milk
		],
		snack: I("pavbhaji", "Pav Bhaji")
	},
	{
		breakfast: [
			I("pongal", "Pongal"),
			egg,
			banana
		],
		lunch: [
			I("pulao", "Jeera Pulao"),
			I("rasamGarlic", "Garlic Rasam"),
			buttermilk
		],
		dinner: [
			I("friedrice", "Fried Rice"),
			fruit,
			milk
		],
		snack: I("sundal", "Sundal")
	},
	{
		breakfast: [
			I("idli", "Idli"),
			egg,
			banana
		],
		lunch: [
			I("pulao", "Veg Pulao"),
			I("poriyal", "Potato Poriyal"),
			buttermilk
		],
		dinner: [
			I("dal", "Yellow Dal"),
			fruit,
			milk
		],
		snack: I("puff", "Veg Puff")
	},
	{
		breakfast: [
			I("kichadi", "Semiya Kichadi"),
			egg,
			banana
		],
		lunch: [
			I("pulao", "Bagara Pulao"),
			I("dal", "Mysore Dal"),
			buttermilk
		],
		dinner: [
			I("chenna", "Chenna Masala"),
			I("icecream", "Ice Cream"),
			milk
		],
		snack: I("biscuit", "Biscuit")
	},
	{
		breakfast: [
			I("pongal", "Pongal"),
			egg,
			banana
		],
		lunch: [
			I("biryani", "Veg Biryani"),
			I("curdrice", "Curd Rice"),
			I("chips", "Potato Chips")
		],
		dinner: [
			I("dal", "Veg Dal"),
			fruit,
			milk
		],
		snack: I("bun", "Sweet Bun")
	},
	{
		breakfast: [
			I("kichadi", "Semiya Kichadi"),
			egg,
			banana
		],
		lunch: [
			I("pulao", "Corn Pulao"),
			I("kootu", "Kootu"),
			buttermilk
		],
		dinner: [
			I("dal", "Veg Dal"),
			fruit,
			milk
		],
		snack: I("cake", "Cake")
	}
];
function mealItems(menu, course) {
	return course === 0 ? menu.breakfast : course === 1 ? menu.lunch : menu.dinner;
}
//#endregion
//#region src/game/stage.ts
/**
* One maze level. Pure simulation: no DOM, no Math.random, no wall-clock time.
* Given the same seeds and the same inputs on the same ticks it always plays out identically,
* which is what makes replay verification and headless bot playtesting possible.
*/
var Stage = class {
	params;
	layout;
	pf;
	rng;
	player;
	enemies = [];
	foodAt = /* @__PURE__ */ new Map();
	maggiAlive = /* @__PURE__ */ new Set();
	events = [];
	stats = {
		time: 0,
		foodEaten: 0,
		enemiesEaten: 0,
		livesLost: 0,
		maxCombo: 0
	};
	foodTotal;
	snackItem;
	state = "playing";
	time = 0;
	score = 0;
	stomachs;
	hunger = 1;
	combo = 0;
	comboMult = 1;
	lastEat = -99;
	foodLeft;
	exitOpen = false;
	maggiUntil = 0;
	chain = 0;
	invulnUntil = 0;
	sinceFood = 0;
	snackActive = false;
	snackUntil = 0;
	snackSpawned = false;
	warden = null;
	wardenLeaveAt = -1;
	wardenWarned = false;
	queued = NO_DIR;
	constructor(params) {
		this.params = params;
		const { difficulty: diff, weekday, course, mods } = params;
		const menu = MENUS[weekday];
		this.snackItem = menu.snack;
		this.layout = buildLayout(params.layoutSeed, {
			foodCount: diff.foodCount,
			items: mealItems(menu, course),
			maggiCount: 2
		});
		this.pf = new Pathfinder(this.layout.grid);
		this.rng = mulberry32(params.simSeed);
		this.stomachs = params.stomachs;
		for (const f of this.layout.food) this.foodAt.set(f.tile, f);
		for (const m of this.layout.maggi) this.maggiAlive.add(m);
		this.foodTotal = this.foodLeft = this.layout.food.length;
		this.player = makeMover(xOf(START_TILE), yOf(START_TILE), PLAYER_SPEED * mods.speedMul);
		const enemySpeed = PLAYER_SPEED * diff.enemySpeedRatio;
		diff.roster.forEach((kind, i) => {
			this.enemies.push(makeEnemy(i, kind, DEN_TILES[i], enemySpeed, 1.2 + i * diff.releaseInterval));
		});
	}
	open(x, y) {
		return x >= 0 && y >= 0 && x < 19 && y < this.layout.grid.rows && !this.layout.grid.walls[idx(x, y)];
	}
	decidePlayer = (m) => {
		const q = this.queued;
		if ((q.dx !== 0 || q.dy !== 0) && this.open(m.col + q.dx, m.row + q.dy)) {
			m.dx = q.dx;
			m.dy = q.dy;
			return;
		}
		if ((m.dx !== 0 || m.dy !== 0) && this.open(m.col + m.dx, m.row + m.dy)) return;
		m.dx = 0;
		m.dy = 0;
	};
	/** Tile the player is (mostly) standing on. */
	get playerTile() {
		const p = this.player;
		return p.t < .5 ? p.row * 19 + p.col : (p.row + p.dy) * 19 + (p.col + p.dx);
	}
	tick(dt, dir) {
		if (this.state !== "playing") return;
		this.time += dt;
		this.stats.time = this.time;
		this.queued = dir;
		const p = this.player;
		if ((p.dx !== 0 || p.dy !== 0) && dir.dx === -p.dx && dir.dy === -p.dy) reverseMover(p);
		advanceMover(p, dt, this.decidePlayer);
		this.checkPickups();
		if (this.state !== "playing") return;
		const ctx = this.aiContext();
		for (const e of this.enemies) {
			const before = e.mode;
			updateEnemy(e, dt, ctx);
			if (before === "den" && e.mode !== "den") this.events.push({
				t: "release",
				kind: e.kind
			});
		}
		if (this.warden) updateEnemy(this.warden, dt, ctx);
		this.checkCollisions();
		if (this.state === "playing") this.updateTimers(dt);
	}
	aiContext() {
		return {
			grid: this.layout.grid,
			pf: this.pf,
			rng: this.rng,
			now: this.time,
			pTile: this.playerTile,
			pdx: this.player.dx,
			pdy: this.player.dy
		};
	}
	checkPickups() {
		const px = moverX(this.player);
		const py = moverY(this.player);
		const tx = Math.round(px);
		const ty = Math.round(py);
		if (Math.abs(px - tx) + Math.abs(py - ty) > .4) return;
		const tile = idx(tx, ty);
		const food = this.foodAt.get(tile);
		if (food) {
			this.foodAt.delete(tile);
			this.eatFood(food, tx, ty);
		}
		if (this.maggiAlive.delete(tile)) this.eatMaggi();
		if (this.snackActive && tile === this.layout.snack) {
			this.snackActive = false;
			this.score += POINTS.snack;
			this.events.push({
				t: "snack",
				x: tx,
				y: ty,
				pts: POINTS.snack,
				item: this.snackItem
			});
		}
		if (this.exitOpen && tile === this.layout.exit) {
			const underPar = Math.max(0, Math.floor(this.params.difficulty.parTime - this.time));
			const bonus = POINTS.stageClear + underPar * POINTS.perSecondUnderPar + this.stomachs * POINTS.perStomach;
			this.score += bonus;
			this.state = "cleared";
			this.events.push({
				t: "clear",
				bonus
			});
		}
	}
	eatFood(food, x, y) {
		this.foodLeft--;
		this.stats.foodEaten++;
		const window = COMBO_WINDOW + this.params.mods.comboBonus;
		this.combo = this.time - this.lastEat <= window ? this.combo + 1 : 1;
		this.lastEat = this.time;
		this.comboMult = 1 + Math.min(4, Math.floor(this.combo / 5));
		this.stats.maxCombo = Math.max(this.stats.maxCombo, this.combo);
		const pts = POINTS.food * this.comboMult;
		this.score += pts;
		this.hunger = Math.min(1, this.hunger + HUNGER_REFILL);
		this.sinceFood = 0;
		this.wardenWarned = false;
		if (this.warden && this.wardenLeaveAt < 0) this.wardenLeaveAt = this.time + 3;
		this.events.push({
			t: "eat",
			x,
			y,
			pts,
			combo: this.combo,
			mult: this.comboMult,
			item: food.item
		});
		if (this.foodLeft === 0) {
			this.exitOpen = true;
			this.events.push({ t: "exitOpen" });
		}
		if (!this.snackSpawned && this.foodLeft <= Math.floor(this.foodTotal / 2)) {
			this.snackSpawned = this.snackActive = true;
			this.snackUntil = this.time + 12;
			this.events.push({ t: "snackIn" });
		}
	}
	eatMaggi() {
		this.maggiUntil = this.time + this.params.difficulty.maggiSeconds + this.params.mods.maggiBonus;
		this.chain = 0;
		for (const e of this.enemies) frighten(e, this.maggiUntil);
		this.events.push({ t: "maggi" });
	}
	checkCollisions() {
		const px = moverX(this.player);
		const py = moverY(this.player);
		const all = this.warden ? [...this.enemies, this.warden] : this.enemies;
		for (const e of all) {
			if (e.mode === "den" || e.mode === "eaten") continue;
			const dx = moverX(e.m) - px;
			const dy = moverY(e.m) - py;
			if (dx * dx + dy * dy > .32) continue;
			if (e.mode === "scared") {
				const pts = POINTS.enemyBase * 2 ** this.chain;
				this.chain++;
				this.score += pts;
				this.stats.enemiesEaten++;
				e.mode = "eaten";
				this.events.push({
					t: "eatEnemy",
					x: px + .5,
					y: py + .5,
					pts,
					chain: this.chain
				});
			} else if (this.time >= this.invulnUntil) {
				this.loseStomach(e.kind === "warden" ? "warden" : "enemy");
				return;
			}
		}
	}
	loseStomach(cause) {
		this.stomachs--;
		this.stats.livesLost++;
		this.combo = 0;
		this.comboMult = 1;
		this.events.push({
			t: "hit",
			cause
		});
		if (this.stomachs <= 0) {
			this.state = "lost";
			this.events.push({ t: "lost" });
			return;
		}
		this.respawn();
	}
	respawn() {
		const p = this.player;
		p.col = xOf(START_TILE);
		p.row = yOf(START_TILE);
		p.dx = p.dy = 0;
		p.t = 0;
		this.enemies.forEach((e, i) => resetEnemy(e, this.time + 1.4 + i * this.params.difficulty.releaseInterval * .6));
		this.warden = null;
		this.wardenLeaveAt = -1;
		this.maggiUntil = 0;
		this.invulnUntil = this.time + INVULN_SECONDS;
		this.sinceFood = 0;
		this.wardenWarned = false;
	}
	updateTimers(dt) {
		this.hunger -= dt / this.params.difficulty.hungerSeconds;
		if (this.hunger <= 0) {
			this.hunger = .45;
			this.loseStomach("starve");
			return;
		}
		this.sinceFood += dt;
		if (!this.warden && !this.wardenWarned && this.sinceFood >= 9) {
			this.wardenWarned = true;
			this.events.push({ t: "wardenWarn" });
		}
		if (!this.warden && this.sinceFood >= 13) this.spawnWarden();
		if (this.warden && this.wardenLeaveAt >= 0 && this.time >= this.wardenLeaveAt) {
			this.warden = null;
			this.wardenLeaveAt = -1;
			this.events.push({ t: "wardenOut" });
		}
		if (this.maggiUntil > 0 && this.time >= this.maggiUntil) {
			this.maggiUntil = 0;
			this.events.push({ t: "scaredEnd" });
		}
		if (this.snackActive && this.time >= this.snackUntil) this.snackActive = false;
		if (this.combo > 0 && this.time - this.lastEat > 2.2 + this.params.mods.comboBonus) {
			this.combo = 0;
			this.comboMult = 1;
		}
	}
	spawnWarden() {
		const dist = bfsDistances(this.layout.grid, this.playerTile);
		let best = this.layout.floor[0];
		for (const t of this.layout.floor) if (dist[t] > dist[best]) best = t;
		const w = makeEnemy(100, "warden", best, PLAYER_SPEED * this.params.mods.speedMul * .78, 0);
		w.mode = "active";
		this.warden = w;
		this.wardenLeaveAt = -1;
		this.events.push({ t: "wardenIn" });
	}
	/** Hands queued events to the presentation layer. */
	drainEvents() {
		return this.events.splice(0, this.events.length);
	}
};
//#endregion
//#region src/game/run.ts
/**
* A Run is one play session: three courses (Breakfast, Lunch, Dinner) that share stomachs,
* score and perks. It is a small state machine that drives Stage objects and is fully
* deterministic: (config + per-tick inputs + perk picks) => identical outcome.
*/
var INTRO_SECONDS = 1.9;
var CLEAR_SECONDS = 2.4;
var DYING_SECONDS = 1.4;
var Run = class {
	cfg;
	mods = freshModifiers();
	owned = /* @__PURE__ */ new Set();
	events = [];
	log = {
		dirs: [],
		perks: []
	};
	outcomes = [];
	rng;
	phase = "intro";
	stage;
	stageIndex = 0;
	stomachs = 3;
	perkOffer = [];
	tickCount = 0;
	stagesCleared = 0;
	bank = 0;
	banked = false;
	timer = INTRO_SECONDS;
	lastCode = 0;
	totals = {
		food: 0,
		enemies: 0,
		lives: 0,
		maxCombo: 0,
		time: 0
	};
	constructor(cfg) {
		this.cfg = cfg;
		this.rng = mulberry32(hashString(`${cfg.seed}|run`));
		this.stomachs = LEVELS[cfg.level ?? "normal"].stomachs;
		this.startStage();
	}
	get totalScore() {
		return this.bank + (this.banked ? 0 : this.stage.score);
	}
	get finished() {
		return this.phase === "over" || this.phase === "complete";
	}
	get phaseProgress() {
		const total = this.phase === "intro" ? INTRO_SECONDS : this.phase === "clear" ? CLEAR_SECONDS : DYING_SECONDS;
		return 1 - Math.max(0, this.timer) / total;
	}
	setPhase(p, seconds = 0) {
		this.phase = p;
		this.timer = seconds;
		this.events.push({
			t: "phase",
			phase: p
		});
	}
	startStage() {
		const { cfg } = this;
		this.stage = new Stage({
			layoutSeed: hashString(`${cfg.seed}|layout|${this.stageIndex}`),
			simSeed: hashString(`${cfg.seed}|sim|${this.stageIndex}`),
			weekday: cfg.weekday,
			course: this.stageIndex,
			difficulty: stageDifficulty(cfg.weekday, this.stageIndex, cfg.adaptive, cfg.level),
			mods: this.mods,
			stomachs: this.stomachs
		});
		this.banked = false;
		this.events.push({
			t: "stageStart",
			course: this.stageIndex
		});
		this.setPhase("intro", INTRO_SECONDS);
	}
	/** Advance exactly one fixed 1/60s tick. */
	tick(code) {
		if (this.finished) return;
		if (code !== this.lastCode) {
			this.log.dirs.push([this.tickCount, code]);
			this.lastCode = code;
		}
		this.tickCount++;
		switch (this.phase) {
			case "intro":
				if ((this.timer -= .016666666666666666) <= 0) this.setPhase("playing");
				break;
			case "playing":
				this.stage.tick(DT, dirFromCode(code));
				for (const e of this.stage.drainEvents()) this.events.push(e);
				if (this.stage.state === "cleared") this.endStage(true);
				else if (this.stage.state === "lost") this.endStage(false);
				break;
			case "clear":
				if ((this.timer -= .016666666666666666) <= 0) {
					if (this.stageIndex >= COURSE_COUNT - 1) this.setPhase("complete");
					else {
						this.perkOffer = offerPerks(this.rng, this.owned);
						this.setPhase("perk");
					}
				}
				break;
			case "dying": if ((this.timer -= .016666666666666666) <= 0) this.setPhase("over");
		}
	}
	endStage(cleared) {
		const s = this.stage;
		this.bank += s.score;
		this.banked = true;
		this.stomachs = Math.max(0, s.stomachs);
		this.totals.food += s.stats.foodEaten;
		this.totals.enemies += s.stats.enemiesEaten;
		this.totals.lives += s.stats.livesLost;
		this.totals.maxCombo = Math.max(this.totals.maxCombo, s.stats.maxCombo);
		this.totals.time += s.stats.time;
		this.outcomes.push({
			cleared,
			livesLost: s.stats.livesLost,
			time: s.stats.time,
			parTime: s.params.difficulty.parTime
		});
		if (cleared) {
			this.stagesCleared++;
			this.setPhase("clear", CLEAR_SECONDS);
		} else this.setPhase("dying", DYING_SECONDS);
	}
	choosePerk(id) {
		if (this.phase !== "perk") return false;
		const perk = this.perkOffer.find((p) => p.id === id) ?? PERKS.find((p) => p.id === id && this.perkOffer.length === 0);
		if (!perk) return false;
		perk.apply(this.mods);
		this.owned.add(perk.id);
		if (this.mods.extraStomachs > 0) {
			this.stomachs = Math.min(5, this.stomachs + this.mods.extraStomachs);
			this.mods.extraStomachs = 0;
		}
		this.log.perks.push([this.tickCount, id]);
		this.perkOffer = [];
		this.stageIndex++;
		this.startStage();
		return true;
	}
	drainEvents() {
		return this.events.splice(0, this.events.length);
	}
};
/** Longest run the game (and the server's verifier) will simulate: 15 minutes of play. */
var MAX_RUN_TICKS = 54e3;
/**
* Re-simulates a recorded run from its log. Equal results prove the run is reproducible/verifiable.
* `untilTick` stops early, which replays a run that was quit (or abandoned) part-way through.
*/
function replayRun(cfg, log, maxTicks = MAX_RUN_TICKS, untilTick = maxTicks) {
	const run = new Run(cfg);
	const limit = Math.min(maxTicks, untilTick);
	let di = 0;
	let pi = 0;
	let code = 0;
	const applyPerks = () => {
		while (pi < log.perks.length && log.perks[pi][0] <= run.tickCount) run.choosePerk(log.perks[pi++][1]);
	};
	while (!run.finished && run.tickCount < limit) {
		applyPerks();
		while (di < log.dirs.length && log.dirs[di][0] <= run.tickCount) code = log.dirs[di++][1];
		run.tick(code);
	}
	applyPerks();
	return run;
}
//#endregion
//#region server/http.ts
/** Small HTTP helpers for Web-standard Request/Response handlers. */
var HttpError = class extends Error {
	status;
	code;
	extra;
	constructor(status, code, extra = {}) {
		super(code);
		this.status = status;
		this.code = code;
		this.extra = extra;
	}
};
function json(body, status = 200, headers = {}) {
	return new Response(JSON.stringify(body), {
		status,
		headers: {
			"content-type": "application/json; charset=utf-8",
			"cache-control": "no-store",
			...headers
		}
	});
}
function parseCookies(header) {
	const out = {};
	if (!header) return out;
	for (const part of header.split(";")) {
		const i = part.indexOf("=");
		if (i <= 0) continue;
		const k = part.slice(0, i).trim();
		try {
			out[k] = decodeURIComponent(part.slice(i + 1).trim());
		} catch {}
	}
	return out;
}
function cookie(name, value, maxAgeSeconds) {
	return `${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAgeSeconds}`;
}
function clientIp(req) {
	return (req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || req.headers.get("x-real-ip") || "unknown").slice(0, 64);
}
/**
* CSRF guard for state-changing requests: browsers only send cross-site JSON after a CORS preflight
* (which we never approve), and a present Origin header must match this host.
*/
function assertSameOrigin(req) {
	if (!(req.headers.get("content-type") ?? "").toLowerCase().startsWith("application/json")) throw new HttpError(415, "json_required");
	const origin = req.headers.get("origin");
	if (!origin) return;
	const host = req.headers.get("x-forwarded-host") ?? req.headers.get("host") ?? new URL(req.url).host;
	let originHost = "";
	try {
		originHost = new URL(origin).host;
	} catch {}
	if (originHost !== host) throw new HttpError(403, "bad_origin");
}
async function readJson(req, maxBytes = 65536) {
	const text = await req.text();
	if (text.length > maxBytes) throw new HttpError(413, "too_large");
	try {
		return JSON.parse(text);
	} catch {
		throw new HttpError(400, "bad_json");
	}
}
//#endregion
//#region server/moderation.ts
/**
* Nickname moderation: a small blocklist checked after undoing common disguises
* (case, leetspeak digits, separators, repeated letters). It stops casual abuse; anything that slips
* through can be renamed with `npm run admin`.
*/
/** Blocked anywhere in the name. */
var ANYWHERE = [
	"fuck",
	"shit",
	"bitch",
	"cunt",
	"pussy",
	"whore",
	"slut",
	"bastard",
	"asshole",
	"nigger",
	"nigga",
	"faggot",
	"retard",
	"nazi",
	"hitler",
	"porn",
	"penis",
	"vagina",
	"chutiya",
	"chutia",
	"madarchod",
	"bhenchod",
	"behenchod",
	"bhosdi",
	"bsdk",
	"gandu",
	"randi",
	"harami",
	"kamina",
	"lavda",
	"punda",
	"thevdiya",
	"thevidiya",
	"baadu",
	"lanja"
];
/** Short words that hide inside innocent ones ("grapes", "peacock"), so only blocked at the start of a name. */
var AT_START = [
	"rape",
	"cum",
	"tits",
	"boob",
	"dick",
	"cock",
	"lund",
	"loda",
	"otha",
	"kuta",
	"sex"
];
var RESERVED = [
	"admin",
	"administrator",
	"moderator",
	"system",
	"messedup",
	"official",
	"support",
	"warden"
];
var LEET = {
	"0": "o",
	"1": "i",
	"3": "e",
	"4": "a",
	"5": "s",
	"7": "t",
	"8": "b",
	"9": "g",
	$: "s",
	"@": "a"
};
function normalizeForModeration(name) {
	return name.toLowerCase().replace(/[0-9$@]/g, (c) => LEET[c] ?? c).replace(/[^a-z]/g, "").replace(/(.)\1+/g, "$1");
}
var squash = (w) => w.replace(/(.)\1+/g, "$1");
function isNicknameAllowed(name) {
	const n = normalizeForModeration(name);
	if (RESERVED.some((r) => n === squash(r))) return false;
	if (ANYWHERE.some((w) => n.includes(squash(w)))) return false;
	return !AT_START.some((w) => n.startsWith(squash(w)));
}
//#endregion
//#region server/redis.ts
var RedisError = class extends Error {};
var UpstashRedis = class {
	url;
	token;
	fetchImpl;
	constructor(url, token, fetchImpl = (...a) => fetch(...a)) {
		this.url = url;
		this.token = token;
		this.fetchImpl = fetchImpl;
	}
	async post(path, body) {
		const res = await this.fetchImpl(`${this.url.replace(/\/+$/, "")}${path}`, {
			method: "POST",
			headers: {
				authorization: `Bearer ${this.token}`,
				"content-type": "application/json"
			},
			body: JSON.stringify(body)
		});
		const json = await res.json().catch(() => null);
		if (!res.ok) throw new RedisError(`redis ${res.status}: ${JSON.stringify(json)}`);
		return json;
	}
	async cmd(command) {
		const json = await this.post("", command);
		if (!json || json.error) throw new RedisError(json?.error ?? "redis: empty reply");
		return json.result;
	}
	async multi(commands) {
		const json = await this.post("/multi-exec", commands);
		if (!Array.isArray(json)) throw new RedisError(json?.error ?? "redis: bad transaction reply");
		for (const r of json) if (r.error) throw new RedisError(r.error);
		return json.map((r) => r.result);
	}
};
/** HGETALL replies are flat [field, value, field, value, ...] lists. */
function hashFromReply(reply) {
	const out = {};
	if (Array.isArray(reply)) for (let i = 0; i + 1 < reply.length; i += 2) out[String(reply[i])] = String(reply[i + 1]);
	return out;
}
//#endregion
//#region server/store.ts
/**
* Data model in Redis.
*
*   mu:u:<sub>              hash: name, created, streak (JSON), best, days (JSON), att (JSON attempt), banned
*   mu:names                hash: lower-case nickname -> sub   (makes nicknames unique)
*   mu:nick                 hash: sub -> nickname              (leaderboard display)
*   mu:lock:<date>:<sub>    one Daily attempt per account per day (SET NX)
*   mu:b:daily:<date>       sorted set sub -> best verified score that day (expires after 8 days)
*   mu:b:alltime            sorted set sub -> best verified single run
*   mu:b:streak             sorted set sub -> best streak
*   mu:rl:<bucket>:<id>     rate-limit counters
*
* `sub` is Google's stable account ID. No email, name or photo is stored.
*/
var K = {
	user: (sub) => `mu:u:${sub}`,
	names: "mu:names",
	nick: "mu:nick",
	lock: (date, sub) => `mu:lock:${date}:${sub}`,
	daily: (date) => `mu:b:daily:${date}`,
	alltime: "mu:b:alltime",
	streak: "mu:b:streak",
	rate: (bucket, id) => `mu:rl:${bucket}:${id}`
};
var parse = (raw, fallback) => {
	if (!raw) return fallback;
	try {
		return JSON.parse(raw);
	} catch {
		return fallback;
	}
};
async function getUser(redis, sub) {
	const h = hashFromReply(await redis.cmd(["HGETALL", K.user(sub)]));
	if (!h.name) return null;
	return {
		sub,
		name: h.name,
		created: Number(h.created) || 0,
		streak: {
			...emptyStreak(),
			...parse(h.streak, {})
		},
		best: Number(h.best) || 0,
		days: parse(h.days, []),
		att: parse(h.att, null),
		banned: h.banned === "1"
	};
}
/** First sign-in: claim a free random nickname and create the account. */
async function createUser(redis, sub, now, rand = Math.random) {
	for (let i = 0; i < 12; i++) {
		const name = randomNickname(rand);
		if (!isNicknameAllowed(name)) continue;
		if (await redis.cmd([
			"HSETNX",
			K.names,
			name.toLowerCase(),
			sub
		]) !== 1) continue;
		const user = {
			sub,
			name,
			created: now,
			streak: emptyStreak(),
			best: 0,
			days: [],
			att: null,
			banned: false
		};
		await redis.multi([[
			"HSET",
			K.user(sub),
			"name",
			name,
			"created",
			now,
			"streak",
			JSON.stringify(user.streak),
			"best",
			0,
			"days",
			"[]"
		], [
			"HSET",
			K.nick,
			sub,
			name
		]]);
		return user;
	}
	throw new HttpError(503, "no_free_names");
}
async function renameUser(redis, user, name) {
	if (name === user.name) return user;
	if (!isNicknameAllowed(name)) throw new HttpError(422, "name_not_allowed");
	const lower = name.toLowerCase();
	if (await redis.cmd([
		"HSETNX",
		K.names,
		lower,
		user.sub
	]) !== 1) {
		if (await redis.cmd([
			"HGET",
			K.names,
			lower
		]) !== user.sub) throw new HttpError(409, "name_taken");
	}
	const cmds = [[
		"HSET",
		K.user(user.sub),
		"name",
		name
	], [
		"HSET",
		K.nick,
		user.sub,
		name
	]];
	if (user.name.toLowerCase() !== lower) cmds.push([
		"HDEL",
		K.names,
		user.name.toLowerCase()
	]);
	await redis.multi(cmds);
	return {
		...user,
		name
	};
}
/** Fixed-window counter. Throws 429 once `limit` calls happen inside `windowSeconds`. */
async function rateLimit(redis, bucket, id, limit, windowSeconds) {
	const key = K.rate(bucket, id);
	const [count] = await redis.multi([["INCR", key], [
		"EXPIRE",
		key,
		windowSeconds
	]]);
	if (count > limit) throw new HttpError(429, "rate_limited", { retryAfter: windowSeconds });
}
//#endregion
//#region server/daily.ts
/**
* The ranked Daily Run, enforced on the server:
*  - the date is the server's (IST), so device clocks do not matter;
*  - each account gets one attempt per day (a Redis lock), across every device and tab;
*  - the day's maze seed is derived from a server secret, so future mazes cannot be computed in advance;
*  - the score is never taken from the client: the server replays the submitted inputs through the same
*    deterministic simulation and records the score that replay produces.
*/
var TICK_HZ = 60;
/** A finish may arrive late (offline, closed tab), but not days later. */
var FINISH_WINDOW_MS = 1296e5;
/** Simulated time can never exceed real elapsed time by more than this (the client cannot run faster than real time). */
var CLOCK_SLACK_SECONDS = 10;
var PERK_IDS = new Set(PERKS.map((p) => p.id));
var serverDate = (now) => istDateKey(now);
function dailySeed(date, secret) {
	return createHmac("sha256", `seed|${secret}`).update(date).digest().readUInt32BE(0);
}
async function startDaily(redis, user, levelRaw, secret, now) {
	const level = LEVEL_IDS.includes(levelRaw) ? levelRaw : null;
	if (!level) throw new HttpError(400, "bad_level");
	if (user.banned) throw new HttpError(403, "banned");
	const date = serverDate(now);
	if (user.att?.date === date) throw new HttpError(409, "already_played");
	const id = randomBytes(12).toString("base64url");
	if (await redis.cmd([
		"SET",
		K.lock(date, user.sub),
		id,
		"NX",
		"EX",
		259200
	]) === null) throw new HttpError(409, "already_played");
	const att = {
		id,
		date,
		weekday: weekdayOf(date),
		level,
		startedAt: now,
		status: "started"
	};
	const streak = recordDailyPlay(user.streak, date);
	await redis.multi([[
		"HSET",
		K.user(user.sub),
		"att",
		JSON.stringify(att),
		"streak",
		JSON.stringify(streak)
	], [
		"ZADD",
		K.streak,
		"GT",
		streak.best,
		user.sub
	]]);
	return {
		result: {
			attemptId: id,
			date,
			weekday: att.weekday,
			level,
			seed: dailySeed(date, secret)
		},
		user: {
			...user,
			att,
			streak
		}
	};
}
/** Rejects anything that is not a plausible input log, before spending CPU on a replay. */
function parseLog(body) {
	const ticks = body.ticks;
	if (!Number.isInteger(ticks) || ticks < 0 || ticks > 54e3) throw new HttpError(400, "bad_ticks");
	const t = ticks;
	const dirsRaw = body.log?.dirs;
	const perksRaw = body.log?.perks;
	if (!Array.isArray(dirsRaw) || !Array.isArray(perksRaw)) throw new HttpError(400, "bad_log");
	if (dirsRaw.length > Math.min(t + 1, 2e4) || perksRaw.length > 2) throw new HttpError(400, "bad_log");
	let prev = -1;
	const dirs = [];
	for (const d of dirsRaw) {
		if (!Array.isArray(d) || d.length !== 2) throw new HttpError(400, "bad_log");
		const [at, code] = d;
		if (!Number.isInteger(at) || at < prev || at > t) throw new HttpError(400, "bad_log");
		if (!Number.isInteger(code) || code < 0 || code > 4) throw new HttpError(400, "bad_log");
		prev = at;
		dirs.push([at, code]);
	}
	const perks = [];
	for (const p of perksRaw) {
		if (!Array.isArray(p) || p.length !== 2) throw new HttpError(400, "bad_log");
		const [at, id] = p;
		if (!Number.isInteger(at) || at < 0 || at > t || typeof id !== "string" || !PERK_IDS.has(id)) throw new HttpError(400, "bad_log");
		perks.push([at, id]);
	}
	return {
		ticks: t,
		log: {
			dirs,
			perks
		}
	};
}
function verifiedScore(att, seed, ticks, log) {
	const run = replayRun({
		mode: "daily",
		seed,
		weekday: att.weekday,
		dateKey: att.date,
		adaptive: 1,
		level: att.level
	}, log, MAX_RUN_TICKS, ticks);
	return {
		score: Math.round(run.totalScore * LEVELS[att.level].score),
		stages: run.stagesCleared
	};
}
async function finishDaily(redis, user, body, secret, now) {
	const att = user.att;
	if (user.banned) throw new HttpError(403, "banned");
	if (!att || att.id !== body.attemptId) throw new HttpError(409, "no_attempt");
	if (att.status === "done") return {
		score: att.score ?? 0,
		stages: att.stages ?? 0,
		rank: att.rank ?? 0,
		best: user.best,
		date: att.date
	};
	if (now - att.startedAt > FINISH_WINDOW_MS) throw new HttpError(410, "attempt_expired");
	const { ticks, log } = parseLog(body);
	if (ticks / TICK_HZ > (now - att.startedAt) / 1e3 + CLOCK_SLACK_SECONDS) throw new HttpError(422, "too_fast");
	const { score, stages } = verifiedScore(att, dailySeed(att.date, secret), ticks, log);
	const best = Math.max(user.best, score);
	const days = [...user.days.filter((d) => d.d !== att.date), {
		d: att.date,
		s: score
	}].filter((d) => daysBetween(d.d, att.date) < 30).slice(-30);
	const done = {
		...att,
		status: "done",
		score,
		stages
	};
	const reply = await redis.multi([
		[
			"ZADD",
			K.daily(att.date),
			"GT",
			score,
			user.sub
		],
		[
			"EXPIRE",
			K.daily(att.date),
			691200
		],
		[
			"ZADD",
			K.alltime,
			"GT",
			score,
			user.sub
		],
		[
			"ZREVRANK",
			K.daily(att.date),
			user.sub
		]
	]);
	const rank = Number(reply[3]) + 1;
	await redis.cmd([
		"HSET",
		K.user(user.sub),
		"att",
		JSON.stringify({
			...done,
			rank
		}),
		"best",
		best,
		"days",
		JSON.stringify(days)
	]);
	return {
		score,
		stages,
		rank,
		best,
		date: att.date
	};
}
//#endregion
//#region server/google.ts
/**
* Verifies a Google Sign-In ID token (an RS256 JWT) without any third-party library:
* the signature is checked against Google's published keys (cached per their Cache-Control),
* then the issuer, audience (our client ID) and expiry are checked.
*/
var SKEW_SECONDS = 60;
var keyCache = /* @__PURE__ */ new Map();
async function loadKeys(url, now, fetchImpl, force = false) {
	const hit = keyCache.get(url);
	if (hit && hit.until > now && !force) return hit.keys;
	const res = await fetchImpl(url);
	if (!res.ok) throw new HttpError(502, "google_keys_unavailable");
	const body = await res.json();
	const keys = /* @__PURE__ */ new Map();
	for (const jwk of body.keys ?? []) {
		if (jwk.kty !== "RSA" || !jwk.kid) continue;
		keys.set(jwk.kid, createPublicKey({
			key: {
				kty: "RSA",
				n: jwk.n,
				e: jwk.e
			},
			format: "jwk"
		}));
	}
	const maxAge = Number(/max-age=(\d+)/.exec(res.headers.get("cache-control") ?? "")?.[1] ?? 3600);
	keyCache.set(url, {
		keys,
		until: now + Math.min(maxAge, 86400) * 1e3
	});
	return keys;
}
var b64json = (part) => {
	try {
		return JSON.parse(Buffer.from(part, "base64url").toString("utf8"));
	} catch {
		throw new HttpError(401, "bad_token");
	}
};
async function verifyGoogleIdToken(token, opts) {
	const now = opts.now ?? Date.now();
	const fetchImpl = opts.fetchImpl ?? ((...a) => fetch(...a));
	if (typeof token !== "string" || token.length > 4096) throw new HttpError(400, "bad_token");
	const parts = token.split(".");
	if (parts.length !== 3) throw new HttpError(401, "bad_token");
	const [h, p, s] = parts;
	const header = b64json(h);
	if (header.alg !== "RS256" || typeof header.kid !== "string") throw new HttpError(401, "bad_token");
	let keys = await loadKeys(opts.jwksUrl, now, fetchImpl);
	if (!keys.has(header.kid)) keys = await loadKeys(opts.jwksUrl, now, fetchImpl, true);
	const key = keys.get(header.kid);
	if (!key) throw new HttpError(401, "unknown_key");
	if (!verify("RSA-SHA256", Buffer.from(`${h}.${p}`), key, Buffer.from(s, "base64url"))) throw new HttpError(401, "bad_signature");
	const claims = b64json(p);
	const sec = now / 1e3;
	const aud = claims.aud;
	if (!opts.issuers.includes(String(claims.iss))) throw new HttpError(401, "bad_issuer");
	if (Array.isArray(aud) ? !aud.includes(opts.clientId) : aud !== opts.clientId) throw new HttpError(401, "bad_audience");
	if (typeof claims.exp !== "number" || claims.exp + SKEW_SECONDS < sec) throw new HttpError(401, "expired");
	if (typeof claims.iat === "number" && claims.iat - SKEW_SECONDS > sec) throw new HttpError(401, "not_yet_valid");
	if (typeof claims.sub !== "string" || !/^[\w-]{1,255}$/.test(claims.sub)) throw new HttpError(401, "bad_subject");
	return { sub: claims.sub };
}
//#endregion
//#region server/session.ts
/**
* Stateless session cookie: `<base64url payload>.<HMAC-SHA256>` holding the Google account ID and an
* expiry. Costs no database reads; tampering breaks the signature.
*/
var SESSION_COOKIE = "mu_s";
var mac = (secret, payload) => createHmac("sha256", `session|${secret}`).update(payload).digest();
function signSession(sub, secret, now = Date.now()) {
	const payload = Buffer.from(JSON.stringify({
		s: sub,
		e: Math.floor(now / 1e3) + 2592e3
	})).toString("base64url");
	return `${payload}.${mac(secret, payload).toString("base64url")}`;
}
function readSession(token, secret, now = Date.now()) {
	if (!token || token.length > 1024) return null;
	const [payload, sig] = token.split(".");
	if (!payload || !sig) return null;
	const want = mac(secret, payload);
	const got = Buffer.from(sig, "base64url");
	if (got.length !== want.length || !timingSafeEqual(got, want)) return null;
	try {
		const data = JSON.parse(Buffer.from(payload, "base64url").toString("utf8"));
		if (typeof data.s !== "string" || typeof data.e !== "number" || data.e < now / 1e3) return null;
		return data.s;
	} catch {
		return null;
	}
}
function sessionFromRequest(req, secret, now = Date.now()) {
	return readSession(parseCookies(req.headers.get("cookie"))[SESSION_COOKIE], secret, now);
}
var sessionCookie = (token) => cookie(SESSION_COOKIE, token, 2592e3);
var clearSessionCookie = () => cookie(SESSION_COOKIE, "", 0);
//#endregion
//#region server/app.ts
/**
* HTTP API. One handler serves every route (vercel.json rewrites /api/<route> to it):
*
*   GET    /api/me             current player (or null), server time, today's status
*   PATCH  /api/me             change nickname
*   POST   /api/auth           sign in with a Google ID token -> session cookie
*   DELETE /api/auth           sign out
*   POST   /api/daily/start    begin today's ranked attempt
*   POST   /api/daily/finish   submit the input log; the server replays it and records the score
*   GET    /api/leaderboard    board=daily|alltime|streak (cached at the CDN for 30 s)
*/
function routeOf(req) {
	const url = new URL(req.url);
	const q = url.searchParams.get("route");
	if (q) return q;
	return url.pathname.replace(/^\/api\//, "").replace(/\/$/, "").replace("/", "-");
}
async function meView(redis, user, now) {
	const today = serverDate(now);
	const base = {
		serverNow: now,
		today,
		weekday: weekdayOf(today)
	};
	if (!user) return {
		...base,
		user: null
	};
	const att = user.att && user.att.date === today ? user.att : null;
	let rank = att?.rank ?? 0;
	if (att?.status === "done") {
		const r = await redis.cmd([
			"ZREVRANK",
			K.daily(today),
			user.sub
		]);
		if (r !== null) rank = Number(r) + 1;
	}
	return {
		...base,
		user: {
			name: user.name,
			best: user.best,
			streak: {
				current: displayStreak(user.streak, today),
				best: user.streak.best,
				freezes: user.streak.freezes,
				status: streakStatus(user.streak, today)
			},
			days: user.days,
			today: att ? {
				status: att.status,
				attemptId: att.id,
				level: att.level,
				score: att.score ?? 0,
				stages: att.stages ?? 0,
				rank
			} : null
		}
	};
}
async function requireUser(req, deps, redis, now) {
	const sub = sessionFromRequest(req, deps.env.secret, now);
	if (!sub) throw new HttpError(401, "signed_out");
	const user = await getUser(redis, sub);
	if (!user) throw new HttpError(401, "signed_out");
	return user;
}
async function leaderboard(req, redis, now) {
	const q = new URL(req.url).searchParams;
	for (const k of q.keys()) if (k !== "board" && k !== "date" && k !== "route") throw new HttpError(400, "bad_param");
	const board = q.get("board");
	const today = serverDate(now);
	let key;
	let date = null;
	if (board === "daily") {
		date = q.get("date") ?? today;
		if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || ![0, 1].includes(daysBetween(date, today))) throw new HttpError(400, "bad_date");
		key = K.daily(date);
	} else if (board === "alltime" && !q.has("date")) key = K.alltime;
	else if (board === "streak" && !q.has("date")) key = K.streak;
	else throw new HttpError(400, "bad_board");
	const flat = (await redis.cmd([
		"ZRANGE",
		key,
		0,
		19,
		"REV",
		"WITHSCORES"
	]) ?? []).map(String);
	const subs = [];
	const scores = [];
	for (let i = 0; i + 1 < flat.length; i += 2) {
		subs.push(flat[i]);
		scores.push(Number(flat[i + 1]));
	}
	const names = subs.length ? await redis.cmd([
		"HMGET",
		K.nick,
		...subs
	]) ?? [] : [];
	const entries = subs.map((_, i) => ({
		name: names[i] ?? "???",
		score: scores[i]
	}));
	return json({
		board,
		date,
		entries
	}, 200, { "cache-control": "public, s-maxage=30, stale-while-revalidate=60" });
}
async function route(req, deps) {
	const { env, redis } = deps;
	const now = (deps.now ?? Date.now)();
	if (!redis || !env.secret) throw new HttpError(503, "not_configured");
	const r = routeOf(req);
	const m = req.method;
	if (m !== "GET" && m !== "HEAD") assertSameOrigin(req);
	if (r === "leaderboard" && m === "GET") return leaderboard(req, redis, now);
	if (r === "me" && m === "GET") {
		const sub = sessionFromRequest(req, env.secret, now);
		const user = sub ? await getUser(redis, sub) : null;
		const headers = sub && !user ? { "set-cookie": clearSessionCookie() } : {};
		return json(await meView(redis, user, now), 200, headers);
	}
	if (r === "me" && m === "PATCH") {
		const user = await requireUser(req, deps, redis, now);
		const body = await readJson(req);
		const name = typeof body.name === "string" ? body.name.trim() : "";
		const problem = nicknameProblem(name);
		if (problem) throw new HttpError(422, "bad_name", { message: problem });
		await rateLimit(redis, "rename", user.sub, 6, 3600);
		return json(await meView(redis, await renameUser(redis, user, name), now));
	}
	if (r === "auth" && m === "POST") {
		await rateLimit(redis, "auth", clientIp(req), 20, 600);
		const body = await readJson(req);
		const { sub } = await verifyGoogleIdToken(String(body.credential ?? ""), {
			clientId: env.googleClientId,
			jwksUrl: env.googleJwksUrl,
			issuers: env.googleIssuers,
			now,
			fetchImpl: deps.fetchImpl
		});
		return json(await meView(redis, await getUser(redis, sub) ?? await createUser(redis, sub, now), now), 200, { "set-cookie": sessionCookie(signSession(sub, env.secret, now)) });
	}
	if (r === "auth" && m === "DELETE") return json({ ok: true }, 200, { "set-cookie": clearSessionCookie() });
	if (r === "daily-start" && m === "POST") {
		const { result, user: next } = await startDaily(redis, await requireUser(req, deps, redis, now), (await readJson(req)).level, env.secret, now);
		return json({
			...result,
			me: await meView(redis, next, now)
		});
	}
	if (r === "daily-finish" && m === "POST") return json(await finishDaily(redis, await requireUser(req, deps, redis, now), await readJson(req, 262144), env.secret, now));
	throw new HttpError(404, "not_found");
}
function createHandler(deps) {
	return async (req) => {
		try {
			return await route(req, deps);
		} catch (e) {
			if (e instanceof HttpError) return json({
				error: e.code,
				...e.extra
			}, e.status);
			console.error("api error", e);
			return json({ error: "server_error" }, 500);
		}
	};
}
var GOOGLE_ISSUERS = ["accounts.google.com", "https://accounts.google.com"];
function readEnv(env = process.env) {
	const redisUrl = env.UPSTASH_REDIS_REST_URL ?? env.KV_REST_API_URL ?? null;
	const redisToken = env.UPSTASH_REDIS_REST_TOKEN ?? env.KV_REST_API_TOKEN ?? null;
	const production = env.VERCEL_ENV === "production";
	const base = env.SESSION_SECRET ?? redisToken;
	return {
		redisUrl,
		redisToken,
		googleClientId: env.GOOGLE_CLIENT_ID ?? "668491181214-oi3fancc9akdkb6r59tkafrc300ls87v.apps.googleusercontent.com",
		googleJwksUrl: !production && env.TEST_GOOGLE_JWKS_URL || "https://www.googleapis.com/oauth2/v3/certs",
		googleIssuers: !production && env.TEST_GOOGLE_ISSUER ? [env.TEST_GOOGLE_ISSUER] : GOOGLE_ISSUERS,
		secret: base ? createHash("sha256").update(`messed-up|${base}`).digest("hex") : null,
		production
	};
}
//#endregion
//#region server/index.ts
/**
* Vercel Function entry. `npm run build:api` bundles this file (and the game simulation it replays)
* into api/game.js. Do not edit api/game.js by hand.
*/
var env = readEnv();
var handler = createHandler({
	env,
	redis: env.redisUrl && env.redisToken ? new UpstashRedis(env.redisUrl, env.redisToken) : null
});
var GET = handler;
var POST = handler;
var PATCH = handler;
var DELETE = handler;
//#endregion
export { DELETE, GET, PATCH, POST };
